### ISSUE TITLE
Check AppImageUpdate for binary delta updates

### ISSUE THREAD

**Issue by probonopd** [martinrotter/textilosaurus#1]
https://github.com/martinrotter/scipio/blob/f96e1c118c791233508d493d891d4d5ce7f96c61/src/miscellaneous/systemfactory.cpp#L38

Check [AppImageUpdate](https://github.com/AppImage/AppImageUpdate) for binary delta updates (only the parts that have changed between two builds are downloaded). @TheAssassin is currently rewriting it as a C++ library, and we are looking to eventually turn it into a reusable, embeddable Qt library. Would you be interested in using this?

**Comment by martinrotter** [comment]
Hello. Well, currently not for textilosaurus which is just fun project for me, but I will check out what I can do for rssguard.
