### ISSUE TITLE
Change Case

### ISSUE THREAD

**Issue by smaragdus** [martinrotter/textilosaurus#10]
**Suggestion**
An option to change the case of the selected case:

'Edit' - new menu - 'Case' (or 'Selection') with sub-menus:

- _UPPERCASE_
- _lowercase_
- _Title Case_
- _Sentence case_
- _iNVERT cASE_

**Usage**
'Change Case' is a common feature for general purpose text editors and it may be very useful on different occasions.

**Comment by martinrotter** [comment]
Tools -> Text Conversion

**Comment by smaragdus** [comment]
@martinrotter 
I missed it, sorry. However you may enhance it.

**Comment by martinrotter** [comment]
Of course.
