### ISSUE TITLE
Tab Context Menu

### ISSUE THREAD

**Issue by smaragdus** [martinrotter/textilosaurus#11]
**Suggestion**
Right-click on a tab offers commands in drop-down menu, for example:

- _Save file_
- _Save file as_
- _Close tab_
- _Etc_

**Comment by martinrotter** [comment]
![screenshot 2018-01-03 09 25 33](https://user-images.githubusercontent.com/1255302/34513334-16b20252-f068-11e7-9675-5ffbd4438167.png)
