### ISSUE TITLE
Read Only Mode

### ISSUE THREAD

**Issue by smaragdus** [martinrotter/textilosaurus#12]
**Suggestion**
If [Tab Context Menu](https://github.com/martinrotter/textilosaurus/issues/11) is implemented a nice addition to it would be 'Read only' mode which disables editing of the selected tab.

**Example**
Right-click on a tab- new command- 'Read only', which disables editing.

**Usage**
'Read only' mode would be useful for avoiding of accidental unwanted editing.

**Comment by martinrotter** [comment]
![screenshot 2018-01-03 10 10 48](https://user-images.githubusercontent.com/1255302/34514586-62da33f6-f06e-11e7-926b-31bbfa084e78.png)
