### ISSUE TITLE
Filesystem Enhancement

### ISSUE THREAD

**Issue by smaragdus** [martinrotter/textilosaurus#14]
**Suggestion**
'Filesystem' panel should show only supported files, for example ._txt_, ._conf_, _.json_, _.po_, etc.

**Addition**
An option for 'Filesystem' panel to remember last used directory and open it after program restart.

**Example**
Files with extensions that are not supported are not shown in the 'Filesystem' panel.
'Tools' - 'Settings' - 'User interface' - new tab - 'Filesystem' - check box 'Remember last used directory'.

**Comment by martinrotter** [comment]
Will add option to add folders to "favorites list" as well.

**Comment by martinrotter** [comment]
FIxed, supports adding of directories to favorites list, favorites list is sorted, only supported filetypes are visible.
