### ISSUE TITLE
Languages menu too long?

### ISSUE THREAD

**Issue by martinrotter** [martinrotter/textilosaurus#15]
For me 'Language' drop-down menu does not look very graceful, especially when textilosaurus is not in maximized state- it takes all thevertical space. Have you thought of splitting it into two columns?

Cited from @smaragdus

**Comment by martinrotter** [comment]
![screenshot 2017-12-11 13 09 22](https://user-images.githubusercontent.com/1255302/33830461-8b84016c-de74-11e7-8180-dc31888ef2e3.png)

@smaragdus - what you think?

**Comment by smaragdus** [comment]
@martinrotter 
I think the scroll-bar looks nice, a good idea.
I see there is a new release (2017.12.11), I will have a look tonight or tomorrow (I hope so).

**Comment by smaragdus** [comment]
@martinrotter 
I had a look but the language bar is not re-worked as in the screen-shot.
Do you keep a change log? I couldn't find any. The changes are not published in the [Releases](https://github.com/martinrotter/textilosaurus/releases) page.

**Comment by martinrotter** [comment]
New menu is in [master], changelog is available from menu Help -> about or https://github.com/martinrotter/textilosaurus/blob/master/resources/text/CHANGELOG

I think about if we actually need Filter there. Maybe using submenus like in https://www.advanced12d.com/wp-content/uploads/2015/02/MTF_Snippet_Syntax_Highlighting-01-Define_language.png would be enough. What you think?

**Comment by smaragdus** [comment]
A filter would be fine for me- I am not a programmer and I mostly use plain text and markdown. So the filter- "User Defined", will have sub-menu with the languages the user has chosen? Anyway, you may keep the scroll-bar as shown in the prototype (first screen)- it is good-looking and handy.

**Comment by martinrotter** [comment]
Well, as you can see, there is simple list with radio buttons, and if you type something into filter textbox, for example if you type in "tex", then only languages which contain that text will be visible, in this case "BibTex" and "LaTeX" and so on.

Thinking about it, typing some phrases in is probably a lot slower than having submenus with proper accelerator keys. Will try it for myself and compare.

**Comment by martinrotter** [comment]
OK, I change it once more to behave like Notepad++, it also supports accelerator keys and is better integrated with keyboard than previous solution. You simply open the menu and hit first letter of desired highlighter. So for markdown, you simply hit "M" key and proper submenu opens.

![screenshot 2017-12-11 14 51 17](https://user-images.githubusercontent.com/1255302/33834335-eb063e12-de82-11e7-883e-527932ea7e74.png)
