### ISSUE TITLE
.LOG function

### ISSUE THREAD

**Issue by midaspt** [martinrotter/textilosaurus#17]
#### Brief description of the issue.

In MS **Notepad**, when a plain text file first line contains the string "_.LOG_", each time that file is opened, a time-stamp will be added.

#### How to reproduce the bug?

1.  Open any text file with a line starting with "_.LOG_";
2.  A default or user-formatted time-stamp gets appended/inserted along with a double line break.

#### What is the expected result?

An easy way to keep user inputted records.

#### What actually happened?

Nothing.

#### Other information (logs, see Wiki)

Discussion @ [https://www.portablefreeware.com/forums/viewtopic.php?t=23638](https://www.portablefreeware.com/forums/viewtopic.php?t=23638)

**Comment by martinrotter** [comment]
Please, test on latest dev. build.
![screenshot 2018-01-03 13 59 29](https://user-images.githubusercontent.com/1255302/34521511-54df68b4-f08e-11e7-9c7a-de1507854b79.png)

**Comment by martinrotter** [comment]
Make format of inserted timestamp changeable via Settings -> Editor.

**Comment by martinrotter** [comment]
Format is now changeable.
