### ISSUE TITLE
Toolbar icons not visible

### ISSUE THREAD

**Issue by smaragdus** [martinrotter/textilosaurus#5]
**Issue**
The icons in the toolbar are not visible:
![textilosaurus-2017 12 06 - 2017-12-06 - error - 004](https://user-images.githubusercontent.com/9025757/33680256-b145d5a0-dac9-11e7-8e63-2f985d438d1a.png)

**System**
_Windows 8 x64_

**Version**
_2017.12.06-0e93b8d_

**Comment by martinrotter** [comment]
Will test in clean VirtualBox Windows 10 machine.

**Comment by martinrotter** [comment]
Fixed, check with newest dev build, pls.

**Comment by smaragdus** [comment]
@martinrotter 
Toolbar icons problem is fixed, thanks.

I have lots of suggestions but first I need to know whether you intend **textilosaurus** to be a _code editor_ only or a _general purpose text editor_ too.

**Comment by martinrotter** [comment]
Well, I certainly do not want Textilosaurus to be some kind of full-blown IDE. I want it to be simple text editor/quick text viewer. So a bit of both worlds, I guess, but definitely more of simple general text editor than source code IDE. Inspiration from these text editors:
* pluma,
* xed,
* gedit,
* Kate,
* Notepad.

Just write all features you think it could have.
