### ISSUE TITLE
Links Detection

### ISSUE THREAD

**Issue by smaragdus** [martinrotter/textilosaurus#6]
**Suggestion**
An option for automatic detection of links:

_http://_
_https://_
_ftp://_
_mailto:_

'Settings' - 'Editor' - new option- 'Links detection' plus two sub-options'- 'Open links on double click' & 'Open links on 'CTRL+Click'.

**Usage**
Links detection plus an option to open them in default programs would be a handy enhancement for those using **Textilosaurus** as a general purpose text editor. My default text editor- [AkelPad](http://akelpad.sourceforge.net/en/index.php), does that right.

**Comment by martinrotter** [comment]
For me: https://github.com/jacobslusser/ScintillaNET/issues/111

**Comment by martinrotter** [comment]
![screenshot 2017-12-08 12 55 10](https://user-images.githubusercontent.com/1255302/33764990-161232f0-dc17-11e7-8891-4afef70f885b.png)

Is highlighting of URLs on mouse hover enough? Parsing whole input file for finding all URLs (+ re-parsing individual chunks on edit) is relatively expensive operation. On input does some extra work only if you hover it.

So would URL highlighting be enough just for mouse hovering? If you click hovered link it gets opened in default browser.

**Comment by martinrotter** [comment]
6df4fde

**Comment by smaragdus** [comment]
@martinrotter 
I have just checked the link detection- HTTP, FTP and Mailto links are detected and opened just fine, nice job. The Implementation looks similar to [Notepad++](https://notepad-plus-plus.org/), it is good enough for me, thanks.
