### ISSUE TITLE
Full Screen Mode Enhancement

### ISSUE THREAD

**Issue by smaragdus** [martinrotter/textilosaurus#8]
**Suggestion**
An option to trigger 'View fullscreen' via the standard 'F11'- 'F11' toggles 'full screen' on/off or 'Esc' exits 'full screen'. Additionally the menu bar, the tool bar and the status bar may be disabled in full screen mode which in my opinion would be the best option for distraction-free text editing.

**Comment by martinrotter** [comment]
Shortcut can be changed in settings. I am thinking if auto-hiding of toolbar and menu is good idea and I believe it is not. Computer screens are big novadays and lack of space is rare issue. Moreover, I made icon size of toolbar smaller in previous commits. User can also show/hide toolbar/statusbar via keyboard shortcuts too, see settings.

**Comment by smaragdus** [comment]
**@martinrotter** 
For me auto-hiding of bars is not about screen sizes but about full absence of distraction. I use this rarely but yet there are times when I need only a blank page with no graphical elements.  In full screen **Notepad++** hides everything beside the tab bar and the status bar while **AkelPad** hides even the status bar so for distraction-free writing I prefer **AkelPad**.

**Comment by martinrotter** [comment]
I see. I open this and maybe implement tomorrow.

**Comment by smaragdus** [comment]
@martinrotter 
There is even a sub-class of note pads- the so-called [zenware](http://searchunifiedcommunications.techtarget.com/definition/zenware) text editors, for example [FocusWriter](https://gottcode.org/focuswriter/), [Q10](http://baara.com/q10/), [TextRoom](https://code.google.com/archive/p/textroom/), [WriteMonkey](http://writemonkey.com/), etc, which either work only in full screen mode or full screen is on by default. Such text editors are usually dedicated to writers who do not want the slightest graphical distraction.
